.TH netfilter-persistent 8
.SH NAME
netfilter-persistent \- load, flush and save netfilter rule sets
.SH SYNOPSIS
.B netfilter-persistent
start
.PP
.B netfilter-persistent
stop
.PP
.B netfilter-persistent
flush
.PP
.B netfilter-persistent
save
.SH DESCRIPTION
.B netfilter-persistent
uses a set of plugins to load, flush and save netfilter rules at boot and halt time.
Plugins can be written in any suitable language and stored in
.I /usr/share/netfilter-persistent/plugins.d
.SH OPTIONS
.TP
start
Calls all plugins with the
.I start
argument, causing them to load their rules into netfilter.
.TP
stop
If the configuration
.I FLUSH_ON_STOP
is enabled, calls all plugins with the
.I flush
argument, causing them to remove their rules from netfilter.
Otherwise, emits a warning only.
.TP
flush
Calls all plugins with the
.I flush
argument, causing them to remove their rules from netfilter.
.TP
save
Calls all plugins with the
.I save
argument, causing them to save the currently-loaded rules to persistent storage.
.SH PLUGINS
Plugins can be written in any language and are merely executed by
.B netfilter-persistent
with a single argument.
All plugins are stored in
.I /usr/share/netfilter-persistent/plugins.d
.PP
Plugins must implement the
.I start
.I flush
and 
.I save
arguments and must not rely on additional arguments for other functionality.
.br
Plugins must return 0 on success and any other code on failure.
.PP
Plugins are free to use and extend the configuration in
.I /etc/default/netfilter-persistent
and to implement their own configuration files.
.SH FILES
.TP
.I /etc/default/netfilter-persistent
Main configuration file
.TP
.I /usr/share/netfilter-persistent/plugins.d
Plugin directory
.SH COPYRIGHT
Copyright (C) 2009 Simon Richter <sjr@debian.org>
.br
Copyright (C) 2010, 2014 Jonathan Wiltshire <jmw@debian.org>
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.SH AUTHORS
Jonathan Wiltshire <jmw@debian.org>
